language: objective-c
sudo: false
osx_image: xcode8.3
matrix:
  include:
  - os: osx
    env: ACTION=test_ios10
  - os: osx
    env: ACTION=test_ios9
  - os: osx
    env: ACTION=test_tvos10
  - os: osx
    env: ACTION=pod_lint
before_script:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage bootstrap
script:
- bundle exec fastlane $ACTION
env:
  global:
    secure: QMMiDhnweks61BDz/k3ok0flerERQdSvuWSfz1K+VHYqB9Y4WhIexPXIyDheDiyRJCrWmouF9BQ2pObpdumz/KQghAq3Bv6bTgCzbJGyWj03FE0ndikTX/dlV6KjBMcaS7VMHpB+KdV6ttx09CT43kwKR4vW06/vLqvc9I5i8aM=
